# -*- coding: utf-8 -*-
"""Rating column cleaning .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdnipBQmAkDeDyL3NLTxpc26O-WVYN8K
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('df.csv')

df

df.info()

df[df['Rating']!= -1]  #عدد -۱ در ریتینگ معنی بیخودی داره و بیفهموم هست

#دوستان به این تعداد سطرها در هر خروجی توجه کن تا ببینید دقیقا کجای کارید و آیا دستورات شما اجرا میشوند یا خیر؟

df = df[df['Rating']!= -1]  #برابر دیتای اصلی قرار میدیم چون از کاری که کردیم راضی هستیم

df['Rating'][0]  #من میام اولین خونه رو بازخوانی میکنم

df['Rating'][5891]   #من میام آخرین خانه رو بازخوانی میکنم

int(df['Rating'][5891])    #اساتید شاید شما ریتینگهای اعشاری زیاد به دردتون نخوره پس میایم اینتجر میکنم و تبدیل به عدد صحیح میکنم

df['Rating'].apply(int)  #سلاطین من میام در کل ستون اعمال میکنم دستورم رو

df['Rating'] = df['Rating'].apply(int)  #حالا میگم راضیم از کارم اپلای کن بر کل ستون

df['Rating'] #میگویم این ستون رو نشون بده ببینم چیکار کردم... آورین

df   #یه خروجی میگیری میبینی دست گلت رو... و ستون ریتینگت  را